version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      
  test_1:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: cd server && npm install 
          working directory: ./server
      - run: 
          command: cd server && npm test
          working directory: ./server
  test_2:
    executor:
      name: node/default
    steps:
      - checkout
      - run: 
          command: cd client && npm install
          working directory: ./client
      - run: 
          command: cd client && npm test
          working directory: ./client          
workflows:
    build-and-test:
      jobs:
        - build
          filters:
            branches:
              only:
                - master
        - test_1:
            filters:
              branches:
                only:
                  - master
            requires:
              - build
        - test_2:
            filters:
              branches:
                only:
                  - master
            requires:
              - build
